baseURL = "https://balerter.github.io"
languageCode = "en-us"
title = "Balerter - a scipts based alerting system"
theme = "hugo-theme-learn"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Documentation for Balerter"
weight = 1
languageName = "English"

[Languages.ru]
title = "Документация по Balerter"
weight = 2
languageName = "Русский"