# Project information
site_name: Balerter
site_url: https://balertere.com
site_author: Andrey Privalov
site_description: >-
  Script Based Alerting Manager

# Repository
repo_name: balerter/balerter
repo_url: https://github.com/balerter/balerter

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/balerter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/balerter/balerter

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - search:

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - CLI flags: getting-started/cli-flags.md
  - Configuration:
      - About: configuration/about.md
      - Top level sections:
          Scripts: configuration/sections/scripts.md
          Datasources: configuration/sections/datasources.md
          Channels: configuration/sections/channels.md
          Upload Storages: configuration/sections/storages-upload.md
          Core Storages: configuration/sections/storages-core.md
      - Secrets: configuration/secrets.md
      - Example: configuration/example.md
  - Changelog:
      - changelog.md
