# Project information
site_name: Balerter
site_url: https://balerter.com
site_author: Andrey Privalov
site_description: >-
  Script Based Alerting Manager

# Repository
repo_name: Documentation
repo_url: https://github.com/balerter/site
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/balerter/balerter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/balerter/balerter
  analytics:
    provider: google
    property: UA-158205152-1

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - search:

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - quick start: getting-started/quickstart.md
      - installation: getting-started/installation.md
      - CLI flags: getting-started/cli-flags.md
  - Configuration:
      - about: configuration/about.md
      - top level sections:
          root values: configuration/sections/root.md
          scripts: configuration/sections/scripts.md
          datasources: configuration/sections/datasources.md
          channels: configuration/sections/channels.md
          upload storages: configuration/sections/storages-upload.md
          core storages: configuration/sections/storages-core.md
          api: configuration/sections/api.md
          system: configuration/sections/system.md
      - secrets: configuration/secrets.md
      - example: configuration/example.md
  - Core modules:
      - about: core-modules/about.md
      - alert: core-modules/alert.md
      - api: core-modules/api.md
      - chart: core-modules/chart.md
      - datasource:
          - about: core-modules/datasource/about.md
          - clickhouse: core-modules/datasource/clickhouse.md
          - prometheus: core-modules/datasource/prometheus.md
          - postgres: core-modules/datasource/postgres.md
          - mysql: core-modules/datasource/mysql.md
          - loki: core-modules/datasource/loki.md
      - file: core-modules/file.md
      - http: core-modules/http.md
      - kv: core-modules/kv.md
      - log: core-modules/log.md
      - meta: core-modules/meta.md
      - runtime: core-modules/runtime.md
      - storage: core-modules/storage.md
      - test: core-modules/test.md
      - tls: core-modules/tls.md
  - Lua Modules:
      - about: lua-modules/about.md
      - create modules : lua-modules/new.md
      - preset modules: lua-modules/presets.md
  - Scripts:
      - about: scripts/about.md
      - meta tags: scripts/meta-tags.md
      - escalate alerts: scripts/escalate.md
  - Testing: testing/index.md
  - API:
      - about: api/about.md
      - metrics: api/metrics.md
  - Core API:
      - about: core-api/about.md
      - alert: core-api/alert.md
      - tls: core-api/tls.md
      - datasource: core-api/datasource.md
      - kv: core-api/kv.md
      - log: core-api/log.md
      - runtime: core-api/runtime.md
      - chart: core-api/chart.md
  - Changelog: changelog.md
