# Project information
site_name: Balerter
site_url: https://balertere.com
site_author: Andrey Privalov
site_description: >-
  Script Based Alerting Manager

# Repository
repo_name: balerter/balerter
repo_url: https://github.com/balerter/balerter

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/balerter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/balerter/balerter

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

plugins:
  - search:

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Quick Start: getting-started/quickstart.md
      - Installation: getting-started/installation.md
      - CLI flags: getting-started/cli-flags.md
  - Configuration:
      - About: configuration/about.md
      - Top level sections:
          Root values: configuration/sections/root.md
          Scripts: configuration/sections/scripts.md
          Datasources: configuration/sections/datasources.md
          Channels: configuration/sections/channels.md
          Upload Storages: configuration/sections/storages-upload.md
          Core Storages: configuration/sections/storages-core.md
          API: configuration/sections/api.md
          System: configuration/sections/system.md
      - Secrets: configuration/secrets.md
      - Example: configuration/example.md
  - Core Modules:
      - About: core-modules/about.md
      - Alert: core-modules/alert.md
      - Api: core-modules/api.md
      - Chart: core-modules/chart.md
      - Datasource:
          - About: core-modules/datasource/about.md
          - Clickhouse: core-modules/datasource/clickhouse.md
          - Prometheus: core-modules/datasource/prometheus.md
          - Postgres: core-modules/datasource/postgres.md
          - MySQL: core-modules/datasource/mysql.md
          - Loki: core-modules/datasource/loki.md
  - Changelog:
      - changelog.md
